// 1. Worst Case Insertions(at End and Beginning) take O(1) time.
// 2. Worst Case deletions(from the Beginning) take O(1) time.
// 3. Insertions and Deletions in the middle are Theta(1) if we have reference to the previous node.
// 4. Round Robin Implementation
// 5 .Merging two sorted Linked Lists is faster than Arrays
// 6. Implementation of simple memory manager where is need to link free blocks is easier
// 7. Easy implementation of Queue and Dequeue Data Structures.